### ISSUE TITLE
Type-checking and jump to def bug with nested locals

### ISSUE THREAD

**Issue by azdavis** [carlverge/jsonnet-lsp#14]
Given this:

```jsonnet
local a =
  local b = false;
  2;

a + 3
```

- When jumping from the usage of `a` to its def, it jumps to `b` instead.
- There is a type error because it thinks the type of `a` is a boolean (from `b`).

**Comment by carlverge** [comment]
Fixed in 39b61a1afd3a4e58a60484276837f91bddf5d6b8
