### ISSUE TITLE
Formatting not working properly

### ISSUE THREAD

**Issue by LorisFriedel** [carlverge/jsonnet-lsp#9]
Hello!

First I would like to thank you for your amazing work on this extension, it's really saving me a lot of time when working on some Jsonnet!

However I noticed two bugs I think: when using the latest version (0.1.10) and the previous one (0.1.8), the "implicit plus" feature does not work at all, I tried multiple combination of "disabling/enabling/reloading/restarting VScode" and it never worked, enabled or disable it doesn't touch any exiting + or remove unnecessary ones.

I also noticed that since 0.1.10 the "String style" option where no more applied properly and it always replace simple quotes by double quotes, even when it is explicitly set to simple quotes.

Here is my configuration VSCode version/config:
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:41:48.638Z (2 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Darwin arm64 22.4.0
Sandboxed: No

In my settings.json I only have:
```
"jsonnet.lsp.fmt.stringStyle": "'",
"jsonnet.lsp.fmt.implicitPlus": true
```

And I'm using Golang Jsonnet v0.19.1.

Would you have any idea why it doesn't work as expected?

Thank you for your help!

**Comment by macintacos** [comment]
Definitely seeing the same thing related to it not respecting the `stringStyle` setting.
